apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: k8s-pod-ch01
spec:
  containers:
  - name: nginx
    image: roxsross12/k8s_test_web:latest
    ports:
    - name: http-pod
      containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-pod-ch01-srv
spec:
  type: NodePort
  ports:
  - name: service-http
    port: 80
    targetPort: http-pod
  selector:
    app: k8s-pod-ch01
