apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
  annotations:
    kubernetes.io/change-cause: "Version 3 application gb-frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontned
    spec:
      containers:
      - name: php-redis
        image: nginx
        # ports:
        # - containerPort: 80
