apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
  annotations:
    kubernetes.io/change-cause: "version1 redis"
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: myapp
        image: redis
        ports:
        - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: redis
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
