apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-flask-app-ch05
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-deploy-flask-app-ch05
  
  template:
    metadata:
      labels:
        app: k8s-deploy-flask-app-ch05
    spec:
      containers:
      - name: flask-pod
        # image: localhost/devops_docker_ch05_api:1.0.0
        # imagePullPolicy: Never
        image: miguelpv/devops_docker_ch05_api:1.0.0
        ports:
        - name: flask-http-pod
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata: 
  name: service-flask-app
spec:
  type: NodePort
  ports:
  - name: service-http
    port: 8000
    targetPort: flask-http-pod
  selector:
    app: k8s-deploy-flask-app-ch05
