# Ejemplo de docker compose para WordPress Guestbook

version: '3'
services:
  guestbook:
    image: roxross12/guestbook
    container_name: guestbook
    restart: always
    ports:
      - 81:5000
    depends_on:
      - redis
    networks:
      - net_guestbook
    
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - net_guestbook

networks:
  net_guestbook:
    driver: bridge

# docker-compose up -d รณ especificar archivo
# investigar:
# nginx-proxy: jwilder/nginx-proxy
# ssl: jrcs/letsencrypt-nginx-proxy-companion (inyectar certificados)

# wildcard nip.io y sslip.io