apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-deploy-ch03

  template:
    metadata:
      labels:
        app: k8s-deploy-ch03
    spec:
      containers:
      - name: nginx-pod
        image: roxsross12/k8s_test_web:latest
        ports:
        - name: http-pod
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-deploy-ch03-srv
spec:
  type: NodePort
  ports:
  - name: service-http
    port: 80
    targetPort: http-pod
  selector:
    app: k8s-deploy-ch03
